import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/assets/styles/global.css"
import Providers from "./providers";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "AlugaFácil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppins.variable} antialiased`}
      >
      <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
