import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/assets/styles/global.css";
import 'react-toastify/dist/ReactToastify.css';
import Providers from "./providers";
import QueryProvider from "@/lib/providers/QueryProvider";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "AlugaFácil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppins.variable} antialiased`}
      >
      <Providers>
        <QueryProvider>
          <ToastContainer 
             position="top-right" 
             autoClose={3000} 
             theme="light" 
          />
          <main style={{ minHeight: '100vh' }}>
              {children}
            </main>
        </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}
